export const TILE = 32;
export const MAP_W = 13;
export const MAP_H = 13;
export const CANVAS_W = MAP_W * TILE;
export const CANVAS_H = MAP_H * TILE;
export const TANK_SIZE = 32;
export const BULLET_SIZE = 16;
export const GRID = 16;
export const DIR = { UP: 0, RIGHT: 1, DOWN: 2, LEFT: 3 };
export const TERRAIN = { EMPTY: 0, BRICK: 1, STEEL: 2, GRASS: 3, WATER: 4 };
export const BASE_COL = 6;
export const BASE_ROW = 12;
//# sourceMappingURL=constants.js.map